#########################
# Model Configurations  #
#########################

ROOT: '/home/minghao.fu/workspace/lily/LiLY/data'
LOG: '/home/minghao.fu/workspace/lily/log'
DATASET: 'vary_B_modular_4_9_9'
CHECKPOINT: './fixedB_best_model.ckpt'
LOAD_CHECKPOINT: False
LOG_NAME: "train from scratch"
PROJ_NAME: "climate"

SPLINE:
    OBS_DIM: 1
    OBS_EMBED_DIM: 2
    BOUND: 5
    BINS: 8
    ORDER: 'linear'

VAE:
    GPU: [0]
    CPU: 8
    TRAIN_BS: 64
    VAL_BS: 256
    EPOCHS: 100
    N_VAL_SAMPLES: 1024
    NCLASS: 4
    LAG: 2
    LENGTH: 1
    INPUT_DIM: 9
    DYN_DIM: 8
    DYN_EMBED_DIM: 2
    INFER_MODE: 'F'
    TRANS_PRIOR: 'NP'
    LR: 5.0e-4
    BETA: 2.0e-3
    GAMMA: 2.0e-2
    SIMGA: 1.0e-2
    B_SPARSITY: 8.0e-3
    BIAS: FALSE
    ENC:
        HIDDEN_DIM: 128
    DEC:
        HIDDEN_DIM: 128
        DIST: 'gaussian'
    PIN: TRUE
    GRAD_CLIP: NULL # defualt NULL

MCC:
    FREQ: 0.1
    CORR: 'Pearson' # 'Spearman'

B:
    GRAPH_THRES: 0.01
