#########################
# Model Configurations  #
#########################

ROOT: '/cache_Intel/yifan/video_understanding/'
LOG: '/cache_Intel/yifan/video_understanding/log'
DATASET: 'physics'


VAE:
    GPU: [0]
    CPU: 64
    TRAIN_BS: 32
    VAL_BS: 1024
    EPOCHS: 100
    N_VAL_SAMPLES: 1024
    NCLASS: 29
    LAG: 2
    NUM_DOMAIN: 6
    LENGTH: 1
    INPUT_DIM: 9
    DYN_DIM: 24 #4,6,8,10
    DYN_EMBED_DIM: 3
    OBS_DIM: 0
    OBS_EMBED_DIM: 0
    INFER_MODE: 'F'
    TRANS_PRIOR: 'NP'
    LR: 1.0e-3 #1.0e-3 1.0e-4
    BETA: 0.001
    GAMMA: 40 # 1 10 40
    SIMGA: 1.0e-2
    BIAS: FALSE
    ENC:
        HIDDEN_DIM: 128
    DEC:
        HIDDEN_DIM: 128
        DIST: 'gaussian'
    PIN: TRUE

MCC:
    FREQ: 0.01
    CORR: 'Pearson' # 'Spearman'

#########################
# Dataset Configurations  #
########################
data_names: ['attrs', 'states', 'actions', 'rels']
n_ball: 5
variable_rels: FALSE
n_class: 1
mode: 'rgb'
# Number of episodes
n_rollout: 500
frame_offset: 1
# Number of time steps in one rollout
time_step: 500
# Step size 0.05 s
dt: 0.05
train_valid_ratio: 0.8
# radius
attr_dim: 1
# x, y, xdot, ydot
state_dim: 4
# ddx, ddy
action_dim: 2
# none, spring, rod
relation_dim: 3

# size of the latent causal graph
node_attr_dim: 0
edge_attr_dim: 1
edge_type_num: 3

height_raw: 110
width_raw: 110
height: 64
width: 64
scale_size: 64
crop_size: 64

lim: [-5., 5., -5., 5.]
# CPU
num_workers: 16